version: "3"
services:
  bot-telegram-view:
    build:
      context: ./BotTelegramView
      args:
        environment: local
    ports:
      - "3000:3000"
    volumes:
      - ./BotTelegramView:/opt/app

  bot-telegram-server:
    build:
      context: ./BotTelegramServer
      args:
        environment: development
    restart: always
    depends_on: 
      - bot-telegram-database
    links: 
      - bot-telegram-database
    ports:
      - "5000:5000"
    volumes:
      - ./BotTelegramServer:/opt/api

  bot-telegram-database:
    image: mariadb:10.4.5-bionic
    volumes:
      - ./BotTelegramServer/Database:/var/lib/mysql
    build:
      context: ./BotTelegramServer    
      dockerfile: DockerfileDatabase.Dockerfile
    restart: always
    ports:
      - 3307:3306